In [1]:
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/latest/download/Mambaforge-colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:34
🔁 Restarting kernel...


In [ ]:
!mamba install -c conda-forge rdkit

In [21]:
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import Draw

import numpy as np

IPythonConsole.ipython_useSVG=True
IPythonConsole.drawOptions.addAtomIndices = True
IPythonConsole.molSize = 400,400

# Smiles from JCP 2008

*   C=C/C=C/C=C/C=C/C=C/C=C 
*   C1=CC=CC=C1
*   C12=CC=CC3=C1C(C(C=C3)=CC=C4)=C4C=C2
*   C1(C(C=CC=C2)=C2C=C3)=C3C=CC=C1
*   C12=CC=CC=C1C=C3C(C=CC=C3)=C2
*   C12=C3C4=C5C6=C1C7=CC=C6C=CC5=CC=C4C=CC3=CC=C2C=C7
*   C1(/C=C/C2=CC=CC=C2)=CC=CC=C1
*   C12=CC=CC=C1C=C3C(C=C(C=CC=C4)C4=C3)=C2


In [22]:
all_molecules = ["C=C/C=C/C=C/C=C/C=C/C=C",
                'C1=CC=CC=C1',
                'C12=CC=CC3=C1C(C(C=C3)=CC=C4)=C4C=C2',
                'C1(C(C=CC=C2)=C2C=C3)=C3C=CC=C1',
                'C12=CC=CC=C1C=C3C(C=CC=C3)=C2',
                'C12=C3C4=C5C6=C1C7=CC=C6C=CC5=CC=C4C=CC3=CC=C2C=C7',
                'C1(/C=C/C2=CC=CC=C2)=CC=CC=C1',
                 'C12=CC=CC=C1C=C3C(C=C(C=CC=C4)C4=C3)=C2']

In [28]:
def get_AdjacencyMatrix(s):
  mol = Chem.MolFromSmiles(s)
  # mol
  am = Chem.GetAdjacencyMatrix(mol)
  return np.asarray(am)


In [30]:
for i,s in enumerate(all_molecules):
  am = get_AdjacencyMatrix(s)
  print(s)
  print(am)
  file_ = f"smile{i+1}_AdjacencyMatrix.npy"
  r = {f"smile{i+1}":s,
       "AdjacencyMatrix":am}
  np.save(file_,r,allow_pickle=True)


C=C/C=C/C=C/C=C/C=C/C=C
[[0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0]]
C1=CC=CC=C1
[[0 1 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]
C12=CC=CC3=C1C(C(C=C3)=CC=C4)=C4C=C2
[[0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0

In [32]:
!pwd

/content
